### ISSUE TITLE
Is /go/api/admin/config/config.xml correct?

### ISSUE THREAD

**Issue by mrmanc** [gocd/api.go.cd#108]
The [documentation](https://api.go.cd/16.5.0/#get-configuration) states that you can use `/go/api/admin/config/config.xml` to get the configuration XML, and that `/go/api/admin/config/current.xml` is an alternative. I could not get the former to work, receiving a null pointer exception. In the logs I could see that it was interpreting `config` as an md5 version. Using the `current.xml` version worked perfectly. Are the docs on [this line](https://github.com/gocd/api.go.cd/blob/master/source/includes/configuration/_02-get-historical-snapshot.md.erb#L37) wrong?

**Comment by ketan** [comment]
@mrmanc — I just took a look at [the code](https://github.com/gocd/gocd/blob/d66268572640af5fea7f6ce85ddf41c54f53801b/config/config-server/src/com/thoughtworks/go/service/ConfigRepository.java#L130-L130), and it looks like `config.xml` is indeed incorrect, we'll fix the documentation to reflect this.

In the meanwhile, please use one of the following —

```
GET /go/api/admin/config/current.xml
GET /go/api/admin/config/:md5.xml
```

**Comment by mrmanc** [comment]
@ketan cool… glad it’s not just me! 😃 👍

**Comment by varshavaradarajan** [comment]
@mrmanc, The documentation to get the configuration XML has been fixed. 
Now you can use of the the following.
```
GET /go/api/admin/config.xml
GET /go/api/admin/config/current.xml
GET /go/api/admin/config/:md5.xml
```
