### ISSUE TITLE
Error in authentication example

### ISSUE THREAD

**Issue by aaronsaderholm** [gocd/api.go.cd#178]
I was not able to get the example GoCD authentication code to work using a recent version of GoCD.  It specifies the following CURL command which will return a 404:

![image](https://user-images.githubusercontent.com/2559942/26984372-289c7e42-4d0d-11e7-8545-27a56484dbdd.png)

https://api.gocd.org/current/#basic-authentication

After digging around for awhile I found this under the agents saying the minimum JSON API version should be 4 for /go/api/agents:

![image](https://user-images.githubusercontent.com/2559942/26984315-ecb93f00-4d0c-11e7-8462-c783e38107e7.png)

After changing the accept header to `application/vnd.go.cd.v4+json`, the requests works fine.  I'm not sure if there is something I'm missing here or if this is just an omission.

**Comment by arvindsv** [comment]
@aaronsaderholm You're right. This needs to be changed [here](https://github.com/gocd/api.go.cd/blob/master/source/includes/_020-authentication.md). Feel free to submit a PR if you can.

@varshavaradarajan - Should we use something else which doesn't change so often, for this example? Also, it says the default current version is v1, just before this. Is that even meaningful?
