### ISSUE TITLE
Api url for agents not working

### ISSUE THREAD

**Issue by leoOrion** [gocd/api.go.cd#193]
I have been trying to access the agents from gocd in my project. But the url specified in the api docs keeps giving back a 404 error

curl -u username:password http://gocdurl:port/go/api/agents

Response:

<head>
    <title>
    HTTP ERROR 404 - Go
</title>

**Comment by ketan** [comment]
Please read the example carefully. You're expected to pass in an `Accept:` header to the api call.

**Comment by jpninanjohn** [comment]
Thank you. Sorry I didn't notice it.
