### ISSUE TITLE
Get server health messages Docu omits authentications is required

### ISSUE THREAD

**Issue by jlusiardi** [gocd/api.go.cd#359]
Hi,

the documentation for (Get server health messages)[https://api.gocd.org/19.5.0/#get-server-health-messages] omits the fact, that you have to be authenticated to access the messages.

`curl 'http://127.0.0.1:8153/go/api/server_health_messages' -u 'admin:admin' -H 'Accept: application/vnd.go.cd.v1+json'`returns a json list of messages.

Whereas `curl 'http://127.0.0.1:8153/go/api/server_health_messages' -H 'Accept: application/vnd.go.cd.v1+json'` just says:
```
{
  "message": "You are not authenticated!"
}
```

Greets
Joachim

**Comment by ketan** [comment]
Unless otherwise stated, it's assumed that all calls require authentication. I'll make sure this is mentioned somewhere in the documentation.

**Comment by jlusiardi** [comment]
To be precise, its missing in the example on the right. On the majority (or even all others) of examples the `-u 'username:password'`part is listed.

**Comment by ketan** [comment]
Understood, thank you for the clarification

**Comment by jlusiardi** [comment]
might be closed by #363
