### ISSUE TITLE
Hyperlinks to old API documentation

### ISSUE THREAD

**Issue by ketan** [gocd/api.go.cd#36]
api.go.cd is the canonical URL for latest api documentation. However it is confusing for users who land there from a google search but are using an older version of go.

I'd like to propose something like to help point users in the right direction.

<img width="488" alt="screen shot 2015-07-18 at 12 42 22 pm" src="https://cloud.githubusercontent.com/assets/10598/8760747/09ac6724-2d4b-11e5-9c99-22c51f6bd825.png">

**Open questions:**

* Clearly some of these APIs have been available for a while, in a different format. What should "available since" say in such cases?
* Some APIs for e.g. "update agent" were multiple calls in the older API (delete, disable, enable) how do we deal with such cases?

WDYT?

**Comment by zabil** [comment]
> Clearly some of these APIs have been available for a while, in a different format. What should "available since" say in such cases?

Can't we just mention available since 15.2 and let the figure out the change in format from the previous version documentation?

> Some APIs for e.g. "update agent" were multiple calls in the older API (delete, disable, enable) how do we deal with such cases?

We try linking to the old API at the description section http://api.go.cd/#agents at not at the operation level
